### ISSUE TITLE
OGR / Out of shared memory on Postgres conversion

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/qgis-ogr-gmlas#4]
Conversion works fine on same file for sqlite

```
  geology/AQD_UBA_Station_50.xml > geology ...

    ... to PostGIS format ...
ERROR 1: ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.

ERROR 1: CREATE TABLE "geology"."competentauthorities_approvalmeasurementsystems" ( "ogc_fid" SERIAL, PRIMARY KEY ("ogc_fid"), "ogr_pkid" VARCHAR NOT NULL, "parent_ogr_pkid" VARCHAR NOT NULL, "relatedparty_pkid" VARCHAR )
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.


```

Data file : https://github.com/INSPIRE-MIF/gml_application_schema_toolbox/blob/master/samples/AQD_UBA_Station_50.xml

Also observed on geology/AQD_UBA_SamplingPoint_50.xml

Maybe something to improve on postgres configuration side.

**Comment by rouault** [comment]
I've pushed a fix in ogr2ogr to commit more often when recreating layers since that seem to consume a lot of postgres resources.

**Comment by fxprunayre** [comment]
Works great. Also increased max_locks_per_transaction to 256 on postgres side.
