### ISSUE TITLE
OGR Metadata table name mismatch

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/qgis-ogr-gmlas#5]
Table name on Postgres are usually lower case and with ```_``` and in OGR metadata table they look like CamelCase with ```-``` for ```_``` ?

![image](https://cloud.githubusercontent.com/assets/1701393/19575464/e9cf0fa4-970e-11e6-8398-4bebc7652279.png)

Maybe related to the truncation strategy changes ?

Would be better to have the same names. eg. this https://github.com/INSPIRE-MIF/qgis-ogr-gmlas/blob/master/ogr_relationships_to_fk.sql was used to build Postgres constraints from OGR metadata tables.

**Comment by rouault** [comment]
The transformation of table and field names, called "laundering", is done by the OGR Postgresql driver itself. See the LAUNDER creation option in http://gdal.org/drv_pg.html . One option would be to disable laundering when converting to postgis. Another option would be to add an option in the GMLAS driver to anticipate for the laundering of the OGR PostgreSQL driver.

This is not related to the truncation strategy.

**Comment by fxprunayre** [comment]
Ok, disabling laundering.

**Comment by rouault** [comment]
I've implemented PostgreSQL name laundering by default, as it will probably help for write support : https://github.com/OSGeo/gdal/commit/eb1d1fe78ed9de5335c3ecbc5709c50af5333b7f
